# Generated by Django 4.0.3 on 2022-03-17 23:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movie',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
