# Generated by Django 4.0.3 on 2022-03-17 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_created_date_alter_movie_update_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='created_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='update_date',
        ),
    ]
