# Generated by Django 4.0.3 on 2022-03-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_rename_created_date_movie_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
