# Generated by Django 4.0.3 on 2022-03-18 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
