# Generated by Django 4.0.3 on 2022-03-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='date',
            new_name='creation_date',
        ),
    ]
