# Generated by Django 4.0.3 on 2022-03-18 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_movie_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
