# Generated by Django 4.0.3 on 2022-03-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_actors_movie_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actors',
            name='file',
        ),
        migrations.AddField(
            model_name='actors',
            name='script',
            field=models.FileField(default='', upload_to='files/', verbose_name='Roteiro'),
        ),
    ]
